In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.naive_bayes import GaussianNB

In [2]:
df = pd.read_csv('titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0          892         0       3   
1          893         1       3   
2          894         0       2   
3          895         0       3   
4          896         1       3   

                                           Name     Sex   Age  SibSp  Parch  \
0                              Kelly, Mr. James    male  34.5      0      0   
1              Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0   
2                     Myles, Mr. Thomas Francis    male  62.0      0      0   
3                              Wirz, Mr. Albert    male  27.0      0      0   
4  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1   

    Ticket     Fare Cabin Embarked  
0   330911   7.8292   NaN        Q  
1   363272   7.0000   NaN        S  
2   240276   9.6875   NaN        Q  
3   315154   8.6625   NaN        S  
4  3101298  12.2875   NaN        S

In [3]:
df = df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns')

In [4]:
df

Survived  Pclass     Sex   Age      Fare
0           0       3    male  34.5    7.8292
1           1       3  female  47.0    7.0000
2           0       2    male  62.0    9.6875
3           0       3    male  27.0    8.6625
4           1       3  female  22.0   12.2875
..        ...     ...     ...   ...       ...
413         0       3    male   NaN    8.0500
414         1       1  female  39.0  108.9000
415         0       3    male  38.5    7.2500
416         0       3    male   NaN    8.0500
417         0       3    male   NaN   22.3583

[418 rows x 5 columns]

In [5]:
df['Sex'] = df['Sex'].astype('category')
df['Sex'] = df['Sex'].cat.codes

In [6]:
df

Survived  Pclass  Sex   Age      Fare
0           0       3    1  34.5    7.8292
1           1       3    0  47.0    7.0000
2           0       2    1  62.0    9.6875
3           0       3    1  27.0    8.6625
4           1       3    0  22.0   12.2875
..        ...     ...  ...   ...       ...
413         0       3    1   NaN    8.0500
414         1       1    0  39.0  108.9000
415         0       3    1  38.5    7.2500
416         0       3    1   NaN    8.0500
417         0       3    1   NaN   22.3583

[418 rows x 5 columns]

In [7]:
df.isna().sum()

Survived     0
Pclass       0
Sex          0
Age         86
Fare         1
dtype: int64

In [8]:
df.Age.mean()

30.272590361445783

In [9]:
df['Age'] = df.Age.fillna(df.Age.mean())
df['Age'] 

0      34.50000
1      47.00000
2      62.00000
3      27.00000
4      22.00000
         ...   
413    30.27259
414    39.00000
415    38.50000
416    30.27259
417    30.27259
Name: Age, Length: 418, dtype: float64

In [10]:
df

Survived  Pclass  Sex       Age      Fare
0           0       3    1  34.50000    7.8292
1           1       3    0  47.00000    7.0000
2           0       2    1  62.00000    9.6875
3           0       3    1  27.00000    8.6625
4           1       3    0  22.00000   12.2875
..        ...     ...  ...       ...       ...
413         0       3    1  30.27259    8.0500
414         1       1    0  39.00000  108.9000
415         0       3    1  38.50000    7.2500
416         0       3    1  30.27259    8.0500
417         0       3    1  30.27259   22.3583

[418 rows x 5 columns]

In [11]:
df['Fare'] = df['Fare'].fillna(df['Fare'].median())

In [12]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [13]:
X = df.drop(['Survived'],axis ='columns')
X.shape

(418, 4)

In [14]:
y=df.Survived
y.shape

(418,)

In [15]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [16]:
model = GaussianNB()

In [17]:
model.fit(X_train,y_train)


GaussianNB()

In [18]:
accuracy = model.score(X_test,y_test)
accuracy

1.0

In [20]:
model.predict([[3,0,20,12.28]])  # input variable = # Pclass, Sex, Age, Fare
# array([1]) = Survived
# array([1]) = Not Survived

C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [21]:
import pickle
with open('model_pickle_Naive_Bayes','wb') as f:
    pickle.dump(model,f)

In [22]:
with open('model_pickle_Naive_Bayes','rb') as f:
    mp = pickle.load(f)

In [24]:
mp.predict([[3,0,20,12.28]])

C:\Users\DELL\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)